### ISSUE TITLE
Create a documentation for Email Product benefits

### ISSUE THREAD

**Issue by luisloaiza** [Criptext/documentation#3]
Look at this example

https://products.office.com/en-us/exchange/office-365-message-encryption

cc @mayermm

**Comment by luisloaiza** [comment]
@mayermm lo tienes listo?

**Comment by mayermm** [comment]
Adjunto la version 1.0. Revisemos esto para luego pintarlo bonito y hacerlo entregable mediante un PDF.
[Beneficios de Criptext.docx](https://github.com/Criptext/documentation/files/10194/Beneficios.de.Criptext.docx)
